### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by tfausak** [haskell-actions/run-ormolu#19]
I ran an Ormolu job ([here](https://github.com/tfausak/monadoc/actions/runs/3843318767)) and got this warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: mrkkrp/ormolu-action@v8

**Comment by mrkkrp** [comment]
Thanks for the heads up!

**Comment by mrkkrp** [comment]
I will release a new version soon following a new release of Ormolu.

**Comment by tfausak** [comment]
Thanks!
