### ISSUE TITLE
Stuck when no haskell files

### ISSUE THREAD

**Issue by spaanse** [haskell-actions/run-ormolu#3]
When you run this action on a repository without haskell files, the action will keep on running forever (i.e. until manual stop or timeout). This happens when the ormolu command isn't fed arguments.

suggested fix:
For running ormolu as pre-commit I use the following script:
```sh
#!/bin/sh
if [ $# -eq 0 ]
then
	exit 0
fi
ormolu --mode check $@ 2>/dev/null
result=$?
ormolu --mode inplace $@ 2>/dev/null
exit $result
```

A similar script would probably work for this action, but obviously without the second run that modifies the code

**Comment by mrkkrp** [comment]
Thanks for the report. I think the fix should be pretty simple—if there are no files detected just skip the ormolu call. I'll push a fix as soon as I have time.

**Comment by mrkkrp** [comment]
This is now fixed. Please use the version `v2`.
