### ISSUE TITLE
The glob patterns did not match any source files

### ISSUE THREAD

**Issue by asarkar** [haskell-actions/run-ormolu#31]
Given the following directory structure:
```
haskell-mooc/
├── .github/
│   └── workflows/
│       └── ci.yml
├── Examples
├── Mooc
├── .stack-work
└── Set1.hs
```

where `ci.yml` runs ormolu as follows:
```
- name: 'Check Formatting'
  uses: haskell-actions/run-ormolu@v14
  with:
    mode: check
    pattern: |
      'Examples/*.hs'
      'Mooc/*.hs'
      '*.hs'
```

The build generates the following warning:
> Warning: The glob patterns did not match any source files

GitHub Actions Job: https://github.com/asarkar/haskell-mooc/actions/runs/6977591684/job/18987634282#step:6:16

Ideally, it shouldn't search in hidden directories unless `dotglob` is set, so, it appears to be a bug. Although I'm no JS expert, I noticed what seems to be [an attempt](https://github.com/haskell-actions/run-ormolu/blob/master/dist/index.js#L2192) to convert relative path to absolute, and in doing so, it may be including hidden files.

**Comment by mrkkrp** [comment]
Hello, well, the code you quote is not something I wrote, it is inlined as part of packaging when `index.js` is converted into `dist/index.js`. IIUC the problem is that `Set1.hs` should be matched by the glob and it isn't? How is this related to hidden files? Have you tried removing single quotes around each glob? See https://github.com/haskell-actions/run-ormolu/blob/master/action.yml#L9-L11.

**Comment by asarkar** [comment]
> the problem is that `Set1.hs` should be matched by the glob

`Set1` and `.hs` files in `Examples` and `Mooc`.

> How is this related to hidden files?

Not hidden files. At some point, I thought I saw ormolu picking up files from the `.stack-work` directory.

> tried removing single quotes

I just did, and that worked! In fact, I removed the pattern altogether, and I don't see files from the hidden `.stack-work` directory being included anymore.

I'm happy to close the ticket, but do you think the documentation can be updated to warn the users about not quoting the patterns?

**Comment by mrkkrp** [comment]
`.stack-work` should probably be gitignored.

> but do you think the documentation can be updated to warn the users about not quoting the patterns?

Well, the readme already links to the example in `action.yml`, but maybe it is worth saying it explicitly.

**Comment by mrkkrp** [comment]
Done in 320044b.
