### ISSUE TITLE
It is not clear from the README what the action does

### ISSUE THREAD

**Issue by Martinsos** [haskell-actions/run-ormolu#5]
Thanks for this action!
I think it is not cleat what the actions does -> does it check if all the files are formatted and fails if some of them are not? Or does it actually perform formatting? I guess the latter would not make sense, but still, it might be useful to be explicit about this.

**Comment by mrkkrp** [comment]
Clarified in e6baa11174ffed4bf15af13ddf488b9ceb02837c.

**Comment by Martinsos** [comment]
Awesome!
