### ISSUE TITLE
Newer versions are not available on marketplace

### ISSUE THREAD

**Issue by infrmtcs** [haskell-actions/run-ormolu#7]
While v2 and v2 were published, they're not available on marketplace yet.
https://github.com/marketplace/actions/ormolu-action
![image](https://user-images.githubusercontent.com/1784440/130325353-d1456297-1cf8-4953-82b9-0f965f56cfd6.png)

**Comment by mrkkrp** [comment]
Fixed. BTW, even if a version is not on marketplace you can still use it, just use `@v3` as the version and it'll work. You can even pick an arbitrary commit and put its hash after `@`.
